[server]
mode = "debug"
port = ":3000"

[database]
host = "localhost"
port = "3306"
database = "blog"
username = "blog"
password = "blogPasswd"

[aliyun_oss]
access_key = "LTAI5tBxC6PkeWhTYgvahXhN"
secret_key = "KuinEVkz3tR1v44Q0JAwpNoClrJZH6"
bucket = "blog-leon"
aliyun_server = "oss-cn-chengdu.aliyuncs.com"